# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.2.13
_src_path: gh:epics-containers/deployment-template-argocd
argocd_project: p48-beamline
argocd_server: argocd.diamond.ac.uk
cluster_name_apps: argus
cluster_name_services: pollux
cluster_namespace_apps: p48-beamline
cluster_namespace_services: p48-beamline
deployment_repo: https://github.com/epics-containers/p48-deployment
description: p48 IOC Instances and Services
git_platform: github.com
github_org: epics-containers
ioc_group: p48
logging_url: https://graylog2.diamond.ac.uk/search?rangetype=relative&fields=message%2Csource&width=1489&highlightMessage=&relative=172800&q=pod_name%3A{service_name}*
services_release: 2024.9.1
services_repo: https://github.com/epics-containers/p48-services
