apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: p48
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: p46-beamline
  destination:
    name: argus
    namespace: p48-beamline
  source:
    path: apps
    repoURL: https://github.com/epics-containers/p48-deployment
    targetRevision: main
    helm:
      version: v3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true